export const recipes = [
  {
    id: 'index',
    label: 'contents',
    color: '#F5EDD8',
    accent: '#C4421A',
  },
  {
    id: 'cookies',
    label: '01 — the birthday cookies',
    color: '#FDE8D4',
    accent: '#C4421A',
    chapterNum: '01',
    title: 'the birthday\ncookies',
    chapterSub: 'baked for a boy i liked,\nbefore we were anything.',
    memory: `I had a huge crush on him and didn't know what to do with it — so I baked a whole batch for his birthday. That was high school. That was also when I realised baking was my version of saying something I couldn't say out loud.\n\nHe ate them all. We eventually dated. I still make these exactly the same way.`,
    who: 'high school, 2019',
    recipeTitle: 'birthday cookies',
    recipeSub: 'the ones that started everything',
    ingredients: [
      { name: 'butter, softened', qty: '225g' },
      { name: 'brown sugar', qty: '200g' },
      { name: 'egg + extra yolk', qty: '2' },
      { name: 'vanilla extract', qty: '2 tsp' },
      { name: 'plain flour', qty: '280g' },
      { name: 'chocolate chips', qty: 'generous' },
    ],
    steps: [
      'Brown the butter until nutty and golden. Cool completely.',
      'Beat cooled butter with brown sugar — pale and fluffy, ~3 min.',
      'Add egg, yolk, and vanilla. Mix well.',
      'Fold in flour, then chips. Don\'t overmix.',
      'Chill 30 min. Bake 180°C for 10–12 min. Pull early — they firm as they cool.',
    ],
    secret: 'brown butter. pull early. every time.',
    pageNums: ['2', '3'],
  },
  {
    id: 'banana',
    label: '02 — banana bread',
    color: '#E8F0DD',
    accent: '#4A6741',
    chapterNum: '02',
    title: 'banana\nbread',
    chapterSub: 'first thing i made when\ni got oven access again.',
    memory: `There's something about getting back to a kitchen after a long time without one. The first thing I made was this. Not because it's the most impressive thing I bake — because it felt like coming home.\n\nI brought it back that spring, with brownies. My friends ate everything within a day.`,
    who: 'spring semester',
    recipeTitle: 'banana bread',
    recipeSub: 'a spring ritual',
    ingredients: [
      { name: 'very ripe bananas', qty: '3 large' },
      { name: 'butter, melted', qty: '75g' },
      { name: 'brown sugar', qty: '150g' },
      { name: 'egg', qty: '1' },
      { name: 'plain flour', qty: '190g' },
      { name: 'baking soda + salt', qty: '1 tsp each' },
    ],
    steps: [
      'Mash bananas until smooth — the blacker, the better.',
      'Mix in melted butter, sugar, egg. Stir until combined.',
      'Fold in flour, baking soda, and salt. Lumps are fine.',
      'Pour into loaf tin. Bake at 175°C for 55–60 min.',
      'Test with a skewer. Cool in the tin 10 min before turning out.',
    ],
    secret: 'blacker bananas = more flavour. don\'t skip this.',
    pageNums: ['4', '5'],
  },
  {
    id: 'brownies',
    label: '03 — travel brownies',
    color: '#EDE4F5',
    accent: '#7B5EA7',
    chapterNum: '03',
    title: 'travel\nbrownies',
    chapterSub: 'flew to her country.\nshowed up with these.',
    memory: `My college roommate — the first time we properly met was when I flew to her country on vacation. I showed up with cookies. She didn't know what to make of me.\n\nWe've been inseparable since. The brownies came later that spring. She said they were the best thing she'd eaten all year. I think she was being kind. I also think she was right.`,
    who: 'for her, always',
    recipeTitle: 'travel brownies',
    recipeSub: 'fudgy, dense, portable',
    ingredients: [
      { name: 'dark chocolate (70%)', qty: '200g' },
      { name: 'butter', qty: '140g' },
      { name: 'caster sugar', qty: '280g' },
      { name: 'eggs', qty: '3' },
      { name: 'plain flour', qty: '80g' },
      { name: 'cocoa powder', qty: '30g' },
    ],
    steps: [
      'Melt chocolate and butter together. Cool slightly.',
      'Whisk in sugar, then eggs one by one. Whisk hard — you want a slight sheen.',
      'Fold in flour and cocoa. Barely mix.',
      'Pour into lined 20cm tin. Bake 175°C for 22–25 min.',
      'Still slightly wobbly when you take it out. Let it set fully in the tin.',
    ],
    secret: 'wobbly centre when it comes out = fudgy when it sets.',
    pageNums: ['6', '7'],
  },
  {
    id: 'soup',
    label: "04 — mom's soup",
    color: '#FDE8D4',
    accent: '#C4421A',
    chapterNum: '04',
    title: "mom's\nsoup",
    chapterSub: 'she made this after a full day\nof work. every single week.',
    memory: `She worked full time. She came home tired every night. And still — every week — there was a pot on the stove. She told me once that seeing me demolish a plate of her food, no matter how exhausted she was, made the whole day worth it.\n\nI have my own kitchen next year. This is the first thing I'm learning to make properly.`,
    who: "mom's recipe — still learning",
    recipeTitle: "mom's soup",
    recipeSub: 'still learning this one',
    ingredients: [
      { name: 'add her ingredients here', qty: '—' },
    ],
    steps: [
      'call mom. write everything down this time.',
    ],
    secret: 'ask her to show you in person. once.',
    pageNums: ['8', '9'],
  },
]