export const recipes = [
  {
    id: 'index',
    label: 'contents',
    color: '#FDE8D4',
    accent: '#C4421A',
  },
  {
    id: 'cookies',
    label: '01 — choc chip cookies',
    color: '#FDE8D4',
    accent: '#C4421A',
    chapterNum: '01',
    title: 'choc chip\ncookies',
    chapterSub: 'Default Bake',
    memory: `These were my baking OBSESSION. When I first started falling in love with baking 
    I didn't really have many ideas on what to bake or what people would enjoy so I always resorted to CC cookies. 
    I remember one time I made  huge batch of these to give to my hs boyfriend's birthday when before we dated and I was crushing hard. 
    I would also do random cookie runs in my neighborhood and give them to my friends at the end of senior year. Most recently though, I baked these
    for my roommate the first time we met. I didn't know what gift to bring her so I baked. `,
    who: 'For: the best of people',
    recipeTitle: 'choc chip cookies',
    recipeSub: 'the ones that started everything',
    ingredients: [
      { name: 'granulated sugar', qty: '½ cup (100g)' },
      { name: 'brown sugar, packed', qty: '¾ cup (165g) ( I usually do a bit less of both sugars )' },
      { name: 'salt', qty: '1 tsp' },
      { name: 'unsalted butter, melted', qty: '½ cup (115g)' },
      { name: 'large egg', qty: '1' },
      { name: 'vanilla extract', qty: '1 tsp' },
      { name: 'all-purpose flour', qty: '1¼ cups (155g)' },
      { name: 'baking soda', qty: '½ tsp' },
      { name: 'milk chocolate chunks', qty: '4 oz (110g)' },
      { name: 'dark chocolate chunks', qty: '4 oz (110g)' },
    ],
    steps: [
      'Whisk together sugars, salt, and melted butter until a paste forms with no lumps.',
      'Whisk in egg and vanilla until light ribbons fall off the whisk.',
      'Sift in flour and baking soda, fold with a spatula — don\'t overmix.',
      'Fold in chocolate chunks. Chill dough at least 30 min (overnight for deeper flavor).',
      'Preheat oven to 350°F (180°C). Scoop onto lined baking sheet, 4 inches apart.',
      'Bake 12–15 min until edges barely brown. Cool completely before serving.',
    ],
    secret: 'chill overnight for a more intense toffee-like flavor.',
    pageNums: ['2', '3'],
  },
  {
    id: 'banana',
    label: '02 — banana bread',
    color: '#E8F0DD',
    accent: '#4A6741',
    chapterNum: '02',
    title: 'banana\nbread',
    chapterSub: 'Spring Time Bake',
    memory: `I feel like banana bread is always the "easiest" bake. You take overripe bananas and add eggs,sugar,flour, a rising agent 
    and boom a delicious loaf, but for me its never been that simple. I have no clue if it's me of my dingy oven but I never made a half decent loaf
    till this past spring. Borught it back for my friends and it was recived with such praise. I can do better though, hence the in development. `,
    who: 'spring semester',
    recipeTitle: 'banana bread',
    recipeSub: 'in development',
    ingredients: [
      { name: 'coming soon', qty: '—' },
    ],
    steps: [
      'Recipe in development — add yours here.',
    ],
    secret: 'blacker bananas = more flavour.',
    pageNums: ['4', '5'],
  },
  {
    id: 'brownies',
    label: '03 — brownies',
    color: '#EDE4F5',
    accent: '#7B5EA7',
    chapterNum: '03',
    title: 'brownies',
    chapterSub: 'Spring Time Bake',
    memory: ` Before leaving for spring break I asked my roommate if she wanted an baked good. My sister runs a home bakery so I'd be getting
    access to a working oven for the frst time in forever and needed inspiration. My roommate asked for brownies. Now my sister's home cafe is 
    based on asian inspired flavors, so in the excuse of R&D I made a vietnamese coffee brownie. But I didn't like the cream cheese so I took that out.
    In the end what really shined was the bronwie base itself. I LOVE a rich brownie. This was it`,
    who: 'for her, always',
    recipeTitle: 'brownies',
    recipeSub: 'fudgy, dense, perfect',
    ingredients: [
      { name: 'unsalted butter', qty: '1 cup (227g)' },
      { name: 'dark chocolate chips', qty: '1 cup (6oz)' },
      { name: 'granulated sugar', qty: '1 cup (200g)' },
      { name: 'light brown sugar', qty: '½ cup (95g)' },
      { name: 'dutch-process cocoa powder', qty: '¼ cup + 1 tbsp (30g)' },
      { name: 'black cocoa powder', qty: '¼ cup + 1 tbsp (30g)' },
      { name: 'large eggs, room temp', qty: '3' },
      { name: 'vanilla extract', qty: '1 tsp' },
      { name: 'brewed coffee', qty: '3 tbsp' },
      { name: 'all-purpose flour', qty: '½ cup (60g)' },
      { name: 'kosher salt', qty: '½ tsp' },
    ],
    steps: [
      'Line an 8x8 pan with parchment paper leaving overhang.',
      'Brown butter in a saucepan over medium-high until deep golden brown.',
      'Pour browned butter over chocolate chips. Let sit 3 min then stir until smooth.',
      'In a large bowl whisk sugars, eggs, vanilla, and both cocoa powders until smooth and lightened.',
      'Add butter-chocolate mixture and coffee. Mix until combined.',
      'Add flour and salt. Mix until smooth. Pour into pan.',
      'Bake at 325°F for 45–50 min until top is puffed and center is almost set.',
    ],
    secret: 'brown butter + vietnamese coffee = the whole difference.',
    pageNums: ['6', '7'],
  },
  {
    id: 'lemon-loaf',
    label: '04 — lemon loaf',
    color: '#FEFBD4',
    accent: '#B8A020',
    chapterNum: '04',
    title: 'lemon\nloaf',
    chapterSub: 'add your story here.',
    memory: `Add your memory here.`,
    who: 'For: the best of people',
    recipeTitle: 'lemon loaf',
    recipeSub: 'in development',
    ingredients: [
      { name: 'coming soon', qty: '—' },
    ],
    steps: [
      'Recipe in development — add yours here.',
    ],
    secret: 'add your secret here.',
    pageNums: ['8', '9'],
  },
  {
    id: 'lemon-shortbread',
    label: '05 — lemon shortbread',
    color: '#FEFBD4',
    accent: '#B8A020',
    chapterNum: '05',
    title: 'lemon\nshortbread',
    chapterSub: 'First Impression Bake',
    memory: `On that same trip to meet my roommate, as an overhtinker, I baked a back-up flavor. I needed something to offset the sweet rich chocolate.
    So why not a zesty light biscuit.`,
    who: 'For: the best of people',
    recipeTitle: 'lemon shortbread',
    recipeSub: 'crisp, buttery, citrusy',
    ingredients: [
      { name: 'all-purpose flour', qty: '150g' },
      { name: 'salt', qty: '½ tsp' },
      { name: 'unsalted butter, softened', qty: '115g' },
      { name: 'powdered sugar', qty: '50g' },
      { name: 'lemon zest', qty: '1 tbsp' },
      { name: 'lemon juice', qty: '1 tsp' },
      { name: 'powdered sugar (icing)', qty: '50g' },
      { name: 'lemon juice (icing)', qty: '2 tsp' },
    ],
    steps: [
      'Stir together flour and salt in a small bowl. Set aside.',
      'Beat softened butter until creamy. Add powdered sugar, lemon juice, and zest. Beat until fluffy.',
      'Add flour mixture and mix on low until crumbly dough forms — squeeze to check it holds together.',
      'Press dough into a disc on parchment. Roll to ¼" thick between two sheets.',
      'Chill in fridge for 1 hour until firm.',
      'Preheat oven to 350°F. Cut with a 3" scalloped cutter. Place 1" apart on lined sheet.',
      'Bake 14–15 min until bottom edges lightly brown. Cool completely before icing.',
      'Mix icing sugar and lemon juice. Drizzle over cooled cookies. Top with lemon zest.',
    ],
    secret: 'don\'t skip chilling — it\'s what keeps the shape.',
    pageNums: ['10', '11'],
    
  },
  {
    id: 'plum-torte',
    label: '06 — plum torte',
    color: '#F0E0F0',
    accent: '#8B4A8B',
    chapterNum: '06',
    title: 'plum\ntorte',
    chapterSub: 'The Oopsies.',
    memory: `Um so a bit shameful. Second date with this guy, had told him I liked to bake. We baked this torte. TLDR I ghosted him. COMPLETELY MY FAULT. Soz.
    Anyways I came back to my dorm with a mysterious ziplock bag of what looked like mushy flesh. Not appetizing. Forced my roommate to try nonetheless because it was
    unfortunately, fucking delicious.`,
    who: 'For: the best of people',
    recipeTitle: 'plum torte',
    recipeSub: 'Embarrisingly Delicious',
    ingredients: [
      { name: 'sugar', qty: '¾ to 1 cup' },
      { name: 'unsalted butter, softened', qty: '½ cup' },
      { name: 'unbleached flour, sifted', qty: '1 cup' },
      { name: 'baking powder', qty: '1 tsp' },
      { name: 'pinch of salt', qty: 'optional' },
      { name: 'eggs', qty: '2' },
      { name: 'pitted purple plums, halved', qty: '24 halves' },
      { name: 'sugar, lemon juice, cinnamon', qty: 'for topping' },
    ],
    steps: [
      'Heat oven to 350°F.',
      'Cream the sugar and butter in a bowl.',
      'Add flour, baking powder, salt and eggs. Beat well.',
      'Spoon batter into an 8, 9 or 10 inch springform pan.',
      'Place plum halves skin side up on top of the batter.',
      'Sprinkle lightly with sugar, lemon juice, and about 1 tsp cinnamon.',
      'Bake 1 hour approximately. Cool before serving — plain or with whipped cream.',
    ],
    secret: 'the plums sink in as it bakes. trust it.',
    pageNums: ['12', '13'],
  },
]